spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
server:
    port: 8080
amazon:
    dynamodb:
        endpoint: "https://dynamodb.ap-south-1.amazonaws.com"
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/210372092753/orderProductQueue
