spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
server:
    port: 8080
amazon:
    dynamodb:
        endpoint: "https://dynamodb.ap-south-1.amazonaws.com"
<<<<<<< HEAD
    aws:
        accesskey: "AKIATB6ZHMNI4NU5UGPB"
        secretkey: "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"
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: AKIATB6ZHMNIQXUOQDSF
      secret-key: 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
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/210372092753/orderProductQueue
=======
>>>>>>> a523d649f0073d0ad08d6bde7e810259d3fb389c
